export const events = [
  {
    image: '/images/event1.png',
    title: 'React Conf 2025',
    slug: 'react-conf-2025',
    location: 'San Francisco, CA',
    date: 'May 15-16, 2025',
    time: '9:00 AM - 6:00 PM PST',
    description: 'The official React conference featuring talks from the core team and community leaders.',
  },
  {
    image: '/images/event2.png',
    title: 'ETHGlobal Hackathon',
    slug: 'ethglobal-hackathon',
    location: 'New York, NY',
    date: 'June 20-22, 2025',
    time: '10:00 AM - 8:00 PM EST',
    description: 'Build the future of Web3 in this 48-hour hackathon with $100k in prizes.',
  },
  {
    image: '/images/event3.png',
    title: 'Next.js Conf',
    slug: 'nextjs-conf-2025',
    location: 'Virtual',
    date: 'October 25, 2025',
    time: '11:00 AM - 5:00 PM PST',
    description: 'Discover the latest innovations in Next.js and the future of web development.',
  },
  {
    image: '/images/event4.png',
    title: 'Google I/O Extended',
    slug: 'google-io-extended',
    location: 'Bangalore, India',
    date: 'May 18, 2025',
    time: '9:30 AM - 7:00 PM IST',
    description: 'Community-led event bringing Google I/O announcements and workshops to developers.',
  },
  {
    image: '/images/event5.png',
    title: 'GitHub Universe',
    slug: 'github-universe-2025',
    location: 'San Francisco, CA',
    date: 'November 12-13, 2025',
    time: '8:00 AM - 6:00 PM PST',
    description: 'Two days of collaboration, innovation, and inspiration for developers worldwide.',
  },
  {
    image: '/images/event6.png',
    title: 'AI DevFest',
    slug: 'ai-devfest-2025',
    location: 'Austin, TX',
    date: 'September 8-10, 2025',
    time: '10:00 AM - 7:00 PM CST',
    description: 'Explore cutting-edge AI and machine learning technologies with hands-on workshops.',
  },
];
